# Generated by Django 5.1.2 on 2024-12-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0002_apartment_house_land_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offers",
                to="real_estate.client",
            ),
        ),
    ]
