# Generated by Django 5.1.2 on 2024-12-02 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0003_offer_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtor",
            name="commission_share",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
