# Generated by Django 5.1.2 on 2024-12-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0004_alter_realtor_commission_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="realtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offers",
                to="real_estate.realtor",
            ),
        ),
    ]
