# Generated by Django 5.1.2 on 2024-12-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0005_offer_realtor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="type",
        ),
        migrations.RemoveField(
            model_name="land",
            name="type",
        ),
        migrations.AlterField(
            model_name="apartment",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
