# Generated by Django 5.1.2 on 2024-12-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0006_remove_house_type_remove_land_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="type",
        ),
    ]
