# Generated by Django 5.1.2 on 2024-12-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0007_remove_apartment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="land",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="land",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("land", "Land"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("min_price", models.PositiveIntegerField()),
                ("max_price", models.PositiveIntegerField()),
                ("min_area", models.PositiveIntegerField(blank=True, null=True)),
                ("max_area", models.PositiveIntegerField(blank=True, null=True)),
                ("min_rooms", models.PositiveIntegerField(blank=True, null=True)),
                ("max_rooms", models.PositiveIntegerField(blank=True, null=True)),
                ("min_floor", models.PositiveIntegerField(blank=True, null=True)),
                ("max_floor", models.PositiveIntegerField(blank=True, null=True)),
                ("min_floors", models.PositiveIntegerField(blank=True, null=True)),
                ("max_floors", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.client",
                    ),
                ),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.realtor",
                    ),
                ),
            ],
        ),
    ]
