# Generated by Django 5.1.2 on 2024-12-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "real_estate",
            "0008_alter_apartment_latitude_alter_apartment_longitude_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "need",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.need",
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="real_estate.offer",
                    ),
                ),
            ],
        ),
    ]
