# Generated by Django 5.1.2 on 2024-12-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0009_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="need",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deal",
                to="real_estate.need",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="offer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deal",
                to="real_estate.offer",
            ),
        ),
    ]
