# Generated by Django 5.1.2 on 2024-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0012_alter_deal_need_alter_deal_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting with Client"),
                            ("showing", "Showing"),
                            ("call", "Scheduled Call"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
