# Generated by Django 5.1.2 on 2024-12-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("real_estate", "0015_merge_0013_event_0014_auto_add_default_need"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="need",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deal",
                to="real_estate.need",
            ),
        ),
    ]
